CREATE TABLE Language (
    id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT(NEWID())
    ,Name NVARCHAR(250) NOT NULL
);

CREATE TABLE BooksLanguages (
    Book UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Book] (id)
    ,Language UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Language] (id)
    ,IsPrimaryLanguage BIT NOT NULL
);
